### ISSUE TITLE
Can't write reviews

### ISSUE THREAD

**Issue by mucky-fahmy** [Ebraheem1/Der-Algorithmus2#16]
Severity: high

Reported by: Abdelrahman Fahmy

Description: Even though there is a My Reviews page I, as a user, can't add any reviews; not from my profile page, the venues page or anywhere.

Steps:
1. Login as a user
2. go to my reviews or view venues
3. attempt to find a write reviews button or link anywhere

Expected result:
a button or link to a review page so I could post a review about my experience or past experience

**Comment by Ebraheem1** [comment]
You can't write  any reviews unless you go to a specific business owner page, and write a review about it.
