### ISSUE TITLE
Rating doesn't change

### ISSUE THREAD

**Issue by mucky-fahmy** [Ebraheem1/Der-Algorithmus2#17]
Severity: low

Reported by: Abdelrahman Mohamed

Description: I added two ratings to a business owner and there were two ratings already and that number didn't change

Steps:
1. login as a user
2. view venues
3. click on a business provider
4. add rating and submit

Expected result:
the no. of ratings should change and it doesn't

**Comment by ahmedhamdi96** [comment]
For the rating of the venue to be updated, multiple clients should rate, as a client, you are only allowed 1 rating, if you add a new one, your rating will be updated.

Create another client, and test it out. It should show you the average of the ratings.
