### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Karim1021** [Ebraheem1/Der-Algorithmus2#25]
Severity: medium
Reported by: Karim Khaled
Description: in the search bar when you write what you search for it searches in the description of the venue not on the name of the profile itself for example when i write ! in the search bar it gives me results as there are two exclamation marks in two different profiles

Steps:
1-Home
2-search

**Comment by Ebraheem1** [comment]
yes, your keyword matches the description, the name of the business owner as well as the types that business owner supports all at the same time, bearing in mind that the search is case-sensitive here.
