### ISSUE TITLE
Created a valid user with this password: "$!k99-=./"

### ISSUE THREAD

**Issue by marhkandil** [Ebraheem1/Der-Algorithmus2#30]
1: Severity (medium).
2: Reported by Mariem Kandil.
3: It refuses to create user with a valid password
4: Steps : a. Filled out registration form with this password "$!k99-=./"
b. After submitting it refuses to create an account saying it must contain 1 digit and a special character 
5: Expected : "Process successful" instead got this error: "Error! must contain a digit and a special character"

**Comment by ahmedElqutb** [comment]
This same issue has been reported earlier so this one is just redundant

**Comment by marhkandil** [comment]
ok then I will close it then
