### ISSUE TITLE
Facebook link

### ISSUE THREAD

**Issue by salmaelsheikh** [Ebraheem1/Der-Algorithmus2#31]
1- Severity: low, since it's confusing to the users to have a Facebook button that's supposed to redirect to a Facebook page, and yet it does not.
2- Reported by: Salma Hesham ElSheikh
3- Description: At the bottom of the page, there is a Facebook icon is supposed to redirect us to Facebook page. However,  when we click on it it doesn't redirect to Facebook.
4-Steps to reproduce the issue: -Login to the application
                                                   -Go to the home page
                                                   -Scroll through the page, you'll fine a Facebook button
                                                   -On pressing, it won't redirect to a Facebook page
5-Expected result: it should redirect you to a Facebook page.

**Comment by Zakyyy** [comment]
I am sorry but this is not a bug this links (linkdin,twitter,facebook...) are for the client when he buys the website he will puts his accounts data @salmaelsheikh
