### ISSUE TITLE
Delete Location of a business

### ISSUE THREAD

**Issue by aboushawareb-mariem** [Ebraheem1/Der-Algorithmus2#32]
Sevirity: low
Reported by: Mariem AbouShawareb
Description: In updating information of a business, there is no option to delete a previously specified location.
Steps:
1- log in as a business owner.
2- go to profile
3- Info menu
4- locations
Expected results: Expected to have the option to delete a location that I already have, but could not.

**Comment by ahmedElqutb** [comment]
there is a link with - sign next to every location, clicking this link removes it. Note that a business owner cannot delete his last remaining location.
