### ISSUE TITLE
Phone number doesnt verify correclty

### ISSUE THREAD

**Issue by AhmedAyman1196** [Ebraheem1/Der-Algorithmus2#34]
1- severity:  low
2- By : Ahmed Ayman
3- checking on the phone number isn’t working correctly
4- Steps to recreate this issue
	Step 1 : Make sure you are logged out and Create a new User or business owner.
	Step 2 : when entering your details , enter an invalid phone number for examle a 30 digits phone number
5- Expected : If the mark that shows that the phone number is verified appear it should truly tell if the phone number is correct or not .

**Comment by ahmedtarek2376** [comment]
The tick is not to verify the phone number it just ensures that the number is longer than a minimum length.
