### ISSUE TITLE
twitter redirect

### ISSUE THREAD

**Issue by ramajtourky** [Ebraheem1/Der-Algorithmus2#35]
1- Severity: low, since it's confusing to the users to have a Facebook button that's supposed to redirect to a Twitter page, and yet it does not.
2- Reported by:Ramaj Tourky
3- Description: in the home page, there is a twitter icon that should redirect to twitter page.
However,  when we click on it, it doesn't redirect to twitter.
4-Steps to reproduce the issue: -Login to the application
                                                   -Go to the home page
                                                   -Scroll through the page, you'll find a twitter icon
                                                   -On pressing, it won't redirect to a twitter page
5-Expected result: it should redirect you to a Twitter page.

**Comment by Zakyyy** [comment]
I am sorry but this is not a bug this links (linkdin,twitter,facebook...) are for the client when he buys the website, he will puts his accounts data @ramajtourky
