### ISSUE TITLE
linkedin

### ISSUE THREAD

**Issue by mariamzaki** [Ebraheem1/Der-Algorithmus2#37]
1- Severity: low
2- Reported by: Mariam zaki
3- Description: At the bottom of the page, there is a linkedin icon is supposed to redirect us to linkedin page. However,  when we click on it it doesn't redirect to linkedin
4-Steps to reproduce the issue: -Login to the application
                                                   -Go to the home page
                                                   -Scroll through the page, you'll fine a linkedin button
                                                   -On pressing, it won't redirect to a linkedin page
5-Expected result: it should redirect you to a linkedin page.

**Comment by Zakyyy** [comment]
I am sorry but this is not a bug this links (linkdin,twitter,facebook...) are for the client when he buys the website he will puts his accounts data @mariamzaki
