### ISSUE TITLE
Different passwords in user registration form marked as ok 

### ISSUE THREAD

**Issue by marhkandil** [Ebraheem1/Der-Algorithmus2#38]
Severity: low
Reported by:Mariem Kandil
Issue: Different passwords in user registration form marked as ok 
Steps: Created user with matching passwords. After that I changed the first password’s entry to not match the one below it. The correct tick remained though
Expected: The tick remained and after i submitted the form it threw an error message saying non matching passwords

**Comment by Zakyyy** [comment]
Could you give us examples about passwords you used?

**Comment by marhkandil** [comment]
First I typed in these two matching passwords:
1!abcdef
1!abcdef
the ticks showed up just fine.
Afterwards I changed the top password to 1!abcdee
The ticks remained
