### ISSUE TITLE
Trips

### ISSUE THREAD

**Issue by mariamzaki** [Ebraheem1/Der-Algorithmus2#45]
1- Severity: Medium
2- Reported by: Mariam zaki, Ramaj Tourky
3- Description: when we go to the trips activity we dont find any trips however in the room-escaping we find trips.
4-Steps to reproduce the issue: -Login to the application
                                                   -Go to the home page
                                                   -Click on Room-Escaping
                                                   -Click on ''?'' then view activities
5-Expected result: Room-Escaping activity but trip activities appear

**Comment by ahmedtarek2376** [comment]
Clicking on room-escaping will show you all the Businesses that have room-escaping activities, however that Business can still have other activities like trips and paintball.
