### ISSUE TITLE
editing Activity

### ISSUE THREAD

**Issue by mohamedazab** [Ebraheem1/Der-Algorithmus2#46]
1- Severity: Low
2- mohamedazab
3- editing activity requires the all the clients to cancel their reservation
4- Steps to recreate this issue.
	1-login as a business owner 
        2-view my activities (click username ->view activities)
        3-choose an activity with reservations 
        4-click edit
5-expected better way to allow the owner to edit with notifying the users with reservations

**Comment by ahmedhamdi96** [comment]
This is not a bug!
This is your suggestion, this is supposed to be a bug report for features that are not working, not your opinion on how we should handle things.

For customers to make a reseravtion, they should pay, which means that a service was sold to them per an agreement on the activity details, the activity should never be edited by the business owner after that. After a legal payment is made, the  legal agreement parties cannot change the conditions agreed upon, this is actually for maintaining integrity.

**Comment by mohamedazab** [comment]
Ok since i partially agree with you I did make the severity of the issue low but since i do not care about this issue that much i will close it BTW it was clearly stated in the post on sems that this is not a bug in the code.
