### ISSUE TITLE
Two business owners can have the same username.

### ISSUE THREAD

**Issue by nourhanShafik** [Ebraheem1/Der-Algorithmus2#53]
Severity: High

Reported by: Nourhan Shafik.

Description:
Submitting 2 different business application with the same username and 2 different business users are created..

Steps to reproduce the issue:
-Go to join us and create an application.
-Click ‘Submit.’
-Do the same again with the same username.

Expected result:
Either one business owner with multiple applications or preventing using the same username.
![2usernames](https://cloud.githubusercontent.com/assets/25374254/25590469/fe2c65ac-2eb0-11e7-972a-8505a237a5b1.png)

**Comment by ahmedtarek2376** [comment]
This is the Business name and not the username.

**Comment by nourhanShafik** [comment]
Then, here as an admin, you are viewing the business owners with their name (which is not unique), what if they are all having the same name, will you have to check everyone to be able to validate them ?
________________________________
