### ISSUE TITLE
Choosing appropriate package

### ISSUE THREAD

**Issue by danielamir1** [Ebraheem1/Der-Algorithmus2#55]
Severity: Low
Reported by: Daniel Amir

Description: When you go into Room-Escaping and view the activities of provider1 and reserve the Room-Escaping, there is only one package only with a fixed number of participants that cannot be changed, what if we are more than 2 players. I guess this should have more options and maybe a max. number or participants. as 2 is the only option.

Steps:
1. Homepage
2. Room-Escaping
3. Provider1
4. View activities
5. Room-Escaping (Press reserve)
6. Choose appropriate package (Only one option is available which doesn't make sense as we could be more than 2.)

**Comment by ahmedtarek2376** [comment]
This is for the Business Owner to decide the packages he has. For example, an escape room will be of a specific price for 4 people and for another price for 5 people, however the room can't have more than 5 people or less than 4. So packages are for the BO to decide.
