### ISSUE TITLE
in View Reviews: when a normal user tries to access `/reviews` pages crashes

### ISSUE THREAD

**Issue by markrofail** [Ebraheem1/Der-Algorithmus2#57]
**Severity**: medium
**Reported by:** Mark Moheb
**Description:** in View Reviews: when a normal user tries to access `/reviews` pages crashes with the following error

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module userApp due to:
Error: [$injector:modulerr] Failed to instantiate module applicationFormController due to:
Error: [$injector:nomod] Module 'applicationFormController' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.3/$injector/nomod?p0=applicationFormController
```

**Steps to reproduce the issue**
1. login in as a  Client 
2. try to access `/reviews` 

**Expected result** redirect to homepage for example or a 403

**Comment by ahmedtarek2376** [comment]
I tried following your steps and I was redirected to the homepage??

**Comment by markrofail** [comment]
Only after you refresh the page. Please check the console for this error
