### ISSUE TITLE
update info's error message does not make sense

### ISSUE THREAD

**Issue by marhkandil** [Ebraheem1/Der-Algorithmus2#58]
Severity: very low
Reported by: Mariem Kandil
Issue: update info's error message does not make sense
Steps:Tried to use the following email: harr y@gmail.com
Expected: an error saying something like emails cant contain space
Got instead this weird message that doesn't make much sense
Error message showed up: " a part followed by ‘@’ should not contain ‘ ‘. "

**Comment by Zakyyy** [comment]
I don't know what is the bug here, the error message is stating that the part before @ can not contain space ' ' @marhkandil

**Comment by marhkandil** [comment]
I dunno why was it confusing for me at the beginning you are right @Zakyyy sorry about that
